[tool.poetry]
name = "githubrss"
version = "0.1.0"
description = ""
authors = ["sweet <sweet@apple.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.12"
feedgen = "^1.0.0"
crawl4ai = "^0.3.72"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
