# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Fetch GitHub Trending

on:
  schedule:
    - cron: "20 8 * * *"

permissions:
  contents: write

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Fetch GitHub Trending Data..."

      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          poetry run playwright install --with-deps chromium

      - name: Run
        run: |
          # read github trending page
          poetry run python main.py

      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: trending-data
          path: ./data

  deploy_job:
    runs-on: ubuntu-latest
    needs: fetch_data

    steps:
      - name: Download data artifact
        uses: actions/download-artifact@v4
        with:
          name: trending-data
          path: /tmp/data

      - name: Clone website branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Copy data to website
        run: |
          rsync -av --delete /tmp/data/* ./data/

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Update data"
          git push

